// SPDX-FileCopyrightText: Copyright © 2025 AerynOS Developers
//
// SPDX-License-Identifier: MPL-2.0

use chrono::{DateTime, Utc};
use serde::Serialize;

pub mod host;

/// Metadata about a specific version of the software
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Serialize)]
pub struct VersionMetadata {
    /// The version string (e.g. "1.0.0")
    pub version: String,
    /// List of downloadable assets associated with this version
    pub downloads: Vec<VersionedAsset>,
    /// Optional release notes text
    pub release_notes: Option<String>,
    /// Timestamp when this version was released
    pub released_at: Option<DateTime<Utc>>,
}

/// Represents a downloadable asset associated with a specific software version.
/// The discovery of a version is usually bound to encountering
/// a release asset, so we store the version string here.
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Serialize)]
pub struct VersionedAsset {
    /// The URL where this asset can be downloaded from
    pub url: String,

    /// The type/category of this asset
    pub kind: AssetKind,

    /// Timestamp when this asset was first released
    pub released_at: Option<DateTime<Utc>>,

    /// Timestamp when this asset was last modified
    pub updated_at: Option<DateTime<Utc>>,
}

/// Categorizes different types of release assets
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Serialize)]
pub enum AssetKind {
    /// Automatically generated release asset, such as a GitHub release from a tag
    Autogenerated,

    /// Manually uploaded release artifact
    Release,

    /// Cryptographic signature file (e.g. detached GPG signature)
    Signature,

    /// File containing checksums/hashes for verification
    Checksum,
}
